on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: windows-latest
    env:
      tag: v1.0.0
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Check Tag Exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with: 
          tag: ${{ env.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Create Executable
        run: pyinstaller --onefile src/connector.py --name EffectvUpload

      - name: Publish a New Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: dist/EffectvUpload.exe, config.ini.template, README.md
          tag: ${{ env.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}